#!/usr/bin/env bash
# Generate a Homebrew formula for Orion Belt CLI tools from a GitHub Release.
#
# Usage:
#   ./scripts/generate-homebrew-formula.sh v1.0.0
#   ./scripts/generate-homebrew-formula.sh v1.0.0 --repo zrougamed/orion-belt
#
# Writes Formula/orion-belt.rb in the current directory (or $OUT_DIR).
set -euo pipefail

VERSION="${1:?usage: $0 vX.Y.Z [--repo owner/name]}"
REPO="zrougamed/orion-belt"
shift || true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

VERSION_NUM="${VERSION#v}"
OUT_DIR="${OUT_DIR:-Formula}"
mkdir -p "$OUT_DIR"

# Prefer tools archives (osh/ocp/oadmin). Adjust names if release assets change.
ASSET_ARM="orion-belt_tools_${VERSION_NUM}_darwin_arm64.tar.gz"
ASSET_AMD="orion-belt_tools_${VERSION_NUM}_darwin_amd64.tar.gz"
BASE="https://github.com/${REPO}/releases/download/${VERSION}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

fetch_sha() {
  local file="$1" url="$2"
  echo "Downloading $url" >&2
  curl -fsSL -o "$tmpdir/$file" "$url"
  shasum -a 256 "$tmpdir/$file" | awk '{print $1}'
}

SHA_ARM="$(fetch_sha "$ASSET_ARM" "$BASE/$ASSET_ARM")"
SHA_AMD="$(fetch_sha "$ASSET_AMD" "$BASE/$ASSET_AMD")"

cat >"$OUT_DIR/orion-belt.rb" <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/generate-homebrew-formula.sh for ${VERSION}.
# Commit this into github.com/<you>/homebrew-orion-belt.
class OrionBelt < Formula
  desc "Orion Belt PAM CLI tools (osh, ocp, oadmin)"
  homepage "https://orion-belt.dev"
  version "${VERSION_NUM}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${BASE}/${ASSET_ARM}"
      sha256 "${SHA_ARM}"
    end
    on_intel do
      url "${BASE}/${ASSET_AMD}"
      sha256 "${SHA_AMD}"
    end
  end

  def install
    bin.install "osh", "ocp", "oadmin"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/osh --version")
    assert_match version.to_s, shell_output("#{bin}/ocp --version")
    assert_match version.to_s, shell_output("#{bin}/oadmin --version")
  end
end
EOF

echo "Wrote $OUT_DIR/orion-belt.rb"
echo "Next: copy into homebrew-orion-belt and push; users run: brew tap ${REPO%%/*}/orion-belt && brew install orion-belt"
